# Bluetooth
CONFIG_BT=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_BLE=y

# USB
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y

# Power management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

# BLE TX power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# LED Strip driver for status LED
CONFIG_LED_STRIP=y
CONFIG_SPI=y

# Custom BLE Toggle + Encoder to Keys
CONFIG_CUSTOM_BLE_TOGGLE=y

# 旋钮：EC11 驱动 + ZMK sensor 子系统（必须开启）
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_KEYMAP_SENSORS=y
